services:
  - type: web
    name: whatsapp-restaurant-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: PINECONE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: WHAPI_API_URL
        sync: false
      - key: WHAPI_API_TOKEN
        sync: false
